### ISSUE TITLE
Redirecionar para a tela de Login após cadastro

### ISSUE THREAD

**Issue by breno-mariz** [fga-gpp-mds/2018.1-VoxPop-WebApp#131]
# Redirecionar para a tela de Login após cadastro

### Descrição:
Eu como usuário desejo ir à tela de login para que eu possa começar a usar os serviços do site assim que eu fizer meu cadastro.

## Critérios de aceitação
- [x] O a aplicação deve redirecionar o usuário para a tela de login após cadastro bem sucedido.
- [x] A aplicação deve alertar o usuário de que sua conta foi criada com sucesso, caso tenha sido.

**Comment by Eduardolimr** [comment]
Aplicação redireciona corretamente para a página de login, a qual foi colocada um alerta caso o registro foi feito corretamente.
