### ISSUE TITLE
Filtro de login

### ISSUE THREAD

**Issue by breno-mariz** [fga-gpp-mds/2018.1-VoxPop-WebApp#144]
# Filtro de login

### Descrição:
O usuário não deve ter acesso a páginas que requerem autenticação caso não esteja logado.

## Comportamento esperado
Redireciona o usuário para página de login quando o mesmo tenta acessas páginas que requerem autenticação.

## Comportamento atual
Não existe filtro atualmente, o que permite que o usuário acesse qualquer página.

## Critérios de aceitação
- [x] Criar mecanismo de filtro de login
- [x] Ao acessar páginas restritas, o filtro deve redirecionar para a página de login quando não estiver logado.
- [x] O filtro deve permitir acesso a páginas restritas caso esteja logado.

**Comment by filipetoyoshima** [comment]
O mecanismo deve ser feito em um componente global?

**Comment by breno-mariz** [comment]
de preferência sim, se você perceber que essa não seria a melhor solução pode mandar outra mensagem aqui

**Comment by rossicler** [comment]
Como a issue não especificava o tipo de story que seria, eu criei como TS, pois se relacionava a uma technical story. Algum problema?
