### ISSUE TITLE
USF24 Entre em contato conosco

### ISSUE THREAD

**Issue by breno-mariz** [fga-gpp-mds/2018.1-VoxPop-WebApp#145]
# USF24 Entre em contato conosco

### Descrição:
Eu como usuário desejo entrar em contato com os desenvolvedores para fornecer feedback ou fazer perguntas aos desenvolvedores.

## Comportamento esperado
O usuário entra na página de "Entre em contato" e manda uma mensagem para os desenvolvedores 

## Critérios de aceitação
- [x] Criar uma página de "Entre em contato".
- [x] O usuário deve poder digitar uma mensagem para os desenvolvedores.
- [x] A mensagem deve ser encaminhada ao e-mail do projeto.

**Comment by filipetoyoshima** [comment]
Sobre o terceiro critério que diz respeito a mandar um e-mail, esse envio deve ser feito através do front ou vai ser criado um endpoint que direcionará a mesagem à API que então enviará o e-mail?

**Comment by breno-mariz** [comment]
através do front mesmo, não existe necessidade de passar a requisição para o back

**Comment by filipetoyoshima** [comment]
Pelo que eu pesquisei, o Angular não suporta serviço de gerenciamento de e-mails.
Existem algumas alternativas que proveêm serviço de SMTP, como o [SmtpJS](https://www.smtpjs.com/), mas aparentemente todos exigem configuração de ambiente.
Seria bom ter algum auxílio de EPS pra essa US (ou uma alternativa que não implantasse um serviço de e-mail na aplicação).

**Comment by mateusdemorais** [comment]
Acho que uma alternativa seria apenas salvas as mensagens no banco de dados, e acessar via camada de administração da API. O que acha @breno-mariz?

(dessa forma, seria disponibilizado um endpoint para o front utilizar)

**Comment by Lucas362** [comment]
Acredito que a solução do @mateusdemorais seria a mais adequada para o problema proposto

**Comment by Eduardolimr** [comment]
Já estamos usando o endpoint criado no back e o componente está fazendo as requests corretamente com os campos novos adicionados.

**Comment by mateusdemorais** [comment]
A funcionalidade já foi integrada à nossa branch dev, e consecutivamente, ao ambiente de homologação. Sendo assim, vou fechar a issue!
