### ISSUE TITLE
TS06 Aplicar conceitos de usabilidade

### ISSUE THREAD

**Issue by breno-mariz** [fga-gpp-mds/2018.1-VoxPop-WebApp#146]
# TS06 Aplicar conceitos de usabilidade

### Descrição:
Os resultados dos testes de usabilidade devem ser aplicados para melhorar a experiencia do usuário.

## Critérios de aceitação
- [x] Reorganizar fluxo(sidebar incluso)
- [x] Colocar scroll estilizado na sidebar
- [x] Colocar splash screen onde necessário

**Comment by Lucas362** [comment]
Onde encontro o roteiro de usabilidade?

**Comment by breno-mariz** [comment]
o @kleberbritomoreira10, colocou na página do github.io https://docs.voxpop.ml/
