### ISSUE TITLE
USF26 – Ver análise social de uma proposição

### ISSUE THREAD

**Issue by breno-mariz** [fga-gpp-mds/2018.1-VoxPop-WebApp#156]
# USF26 – Ver análise social de uma proposição 

### Descrição:
Eu, como usuário desejo ver análise social de uma proposição para que eu possa saber como cada tipo de pessoa vota uma proposição 

## Critérios de aceitação
- [x] Criar página de proposição
- [ ] Exibir o gráfico de rosquinha para os votos dos deputados
- [x] Exibir o gráfico de barras para a aprovação de uma proposição pela população de acordo com o gênero
- [x] Exibir o gráfico de barras para a aprovação de uma proposição pela população de acordo com a raça
- [x] Exibir o gráfico de barras para a aprovação de uma proposição pela população de acordo com o grau de escolaridade
- [x] Exibir o gráfico de barras para a aprovação de uma proposição pela população de acordo com a renda
- [x] Exibir o gráfico de barras para a aprovação de uma proposição pela população de acordo com a região

**Comment by Eduardolimr** [comment]
Gráfico de rosquinha apresentou alguns problemas. Implementamos um gráfico de barras como os outros.

**Comment by mateusdemorais** [comment]
Certo! Qualquer coisa tentamos mudar depois.
