### ISSUE TITLE
BF12 - Bug cookies autenticação

### ISSUE THREAD

**Issue by breno-mariz** [fga-gpp-mds/2018.1-VoxPop-WebApp#159]
# BF12 - Bug cookies autenticação

## Comportamento esperado
Reconhecer quando o usuário estiver logado.

## Comportamento atual
Aparecendo botão de logar mesmo com o usuário logado.

## Critérios de aceitação
- [ ] Reconhecer que o usuário está logado na página de política de privacidade.
- [ ] Reconhecer que o usuário está logado na página de termos de serviço.

**Comment by Lucas362** [comment]
A página de termos de serviço ainda não foi implementada, devo criar a página?

**Comment by breno-mariz** [comment]
Pode sim Lucas, só tem que dar o PR antes de começarem a página em outra branch
