### ISSUE TITLE
TS05 – Criar página de termos de serviço

### ISSUE THREAD

**Issue by breno-mariz** [fga-gpp-mds/2018.1-VoxPop-WebApp#160]
# TS05 – Criar página de termos de serviço
### Descrição:
Deve ser disponibilizada uma página de termos de serviço ao usuário.

## Critérios de aceitação
- [ ] Criar  termos de serviço
- [ ] Criar página de termos de serviço

**Comment by mateusdemorais** [comment]
Quem for implementar isso, se lembre de gerenciar os cookies na página de forma adequada.

**Comment by mateusdemorais** [comment]
Aproveitem para colocar no registro um texto que indique que ao se cadastrar o usuário concorda com a política de privacidade e com os termos de serviço.
