### ISSUE TITLE
Estudo Angular

### ISSUE THREAD

**Issue by mateusdemorais** [fga-gpp-mds/2018.1-VoxPop-WebApp#34]

**Comment by filipetoyoshima** [comment]
O que faz dessa issue "fechada"?

**Comment by mateusdemorais** [comment]
Como indicamos que os membros de Métodos de Desenvolvimento de Software estudassem tanto Angular quanto DRF, e vimos no Tracker de atividades que esse estudo realmente estava ocorrendo ao longo da Sprint, resolvemos documentar como Issue no GitHub. Será fechada após resolvermos as pendências e a Sprint for efetivamente fechada. @filipetoyoshima

**Comment by affbedran** [comment]
Vou fechar esta issue. Essa pendência já havia sido resolvida.
