### ISSUE TITLE
USF08 – Ver PL Disponíveis

### ISSUE THREAD

**Issue by kleberbritomoreira10** [fga-gpp-mds/2018.1-VoxPop-WebApp#43]
# USF08 – Ver PL Disponíveis

### Descrição:
Eu, como usuário desejo ver lista de PL disponíveis  para que eu possa ter acesso a PLs da aplicação

## Critérios de aceitação

**Comment by filipetoyoshima** [comment]
Precisamos redefinir os critérios de aceitação desta issue com o PO.
