### ISSUE TITLE
USF09 – Ver PL Detalhado

### ISSUE THREAD

**Issue by kleberbritomoreira10** [fga-gpp-mds/2018.1-VoxPop-WebApp#44]
# USF09 – Ver PL Detalhado

### Descrição:
Eu, como usuário desejo ver PL detalhado para que eu possa saber detalhes de um PL específico

## Critérios de aceitação
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by rossicler** [comment]
Em reunião, concordamos que essa US é desnecessária, visto que não existe informações adicionais a serem mostradas
