### ISSUE TITLE
Feedback 01

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-VoxPop-WebApp#5]
O trabalho de vcs está deixando muito a desejar! Algumas evidencias:

- [ ] Vocês não estão exercitando práticas ágeis!

- [ ] Não usam issues para rastrear as atividades

- [ ] Não tem politicas de pull requests - e não estao usando code review!

- [ ] após um mês de aula, não há NENHUMA issue aberta

- [ ] Não há transparência no acompanhamento das sprints

- [ ] não são apresentados indicadores/metricas da sprint

- [ ] Scrum master está fazendo um mal trabalho de acompanhar as boas práticas ágeis.

- [ ] Não tem o roadmap do projeto

- [ ] Não há transparencia em relação aos papéis e atribuições e responsabilidades de cada papel (e todos os papéis de EPS estão sendo mal executados)

- [ ] após um mês de aula, não há uma linha de codigo

**Comment by affbedran** [comment]
Olá professora,

Agradecemos o feedback, e informamos que estamos fazendo o possível para resolver os pontos acima.

Muito obrigado.

**Comment by affbedran** [comment]
Aproveitando a oportunidade, professora @RochaCarla, ainda não temos um coach designado. E estamos precisando de uma opinião externa em certas ocasiões. Na terça-feira passada tínhamos comentado sobre o assunto com a Sra, e ficamos na pendência de uma resposta.

Obrigado pela atenção.
