### ISSUE TITLE
USF17 – Ver Compatibilidade Política

### ISSUE THREAD

**Issue by kleberbritomoreira10** [fga-gpp-mds/2018.1-VoxPop-WebApp#52]
# USF17 – Ver Compatibilidade Política 

### Descrição:
Eu, como usuário desejo ver índice de compatibilidade com um deputado para que eu possa saber minha compatibilidade com um deputado

## Critérios de aceitação
- [x] Criar componente que mostra a compatibilidade
- [x] Adicionar componente aonde necessário

**Comment by rossicler** [comment]
Foi implementado a compatibilidade política dentro dos componentes relacionados aos deputados ja existentes, era esse o objetivo da issue? Ou seria um novo component?

**Comment by breno-mariz** [comment]
A ordem das issues foi trocado com a USF22, por isso o componente já existia quando vocês fizeram esta issue
