### ISSUE TITLE
USF20 - Visualizar últimas proposições

### ISSUE THREAD

**Issue by affbedran** [fga-gpp-mds/2018.1-VoxPop-WebApp#73]
### Descrição:
Eu, como usuário desejo visualizar os últimas proposições votados na câmara para me manter em dia nas decisões políticas do meu país, e poder expressar minha opinião em proposições atuais.

## Critérios de aceitação
- [x] Exibir na parte esquerda da tela os últimos 5 PL
- [x] Exibir as informações das proposições no formato da div de proposições do listar proposições

**Comment by mateusdemorais** [comment]
Na issue está definido como 5 proposições, mas lembro de ter ouvido falarem sobre mostrar 3. Como acham que fica melhor? @rossicler @SamuelMordred @breno-mariz @affbedran @kleberbritomoreira10
